# Generated by Django 5.2.3 on 2025-06-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='file',
            name='unique_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
