# Generated by Django 5.2.3 on 2025-06-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_file_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(),
        ),
    ]
